### ISSUE TITLE
Crafting Table lacks a texture

### ISSUE THREAD

**Issue by PhantomBadger** [Level-5-Pidgey/Expedio#13]
the standard Crafting Table lacks a texture when placed in the world, showing instead the Pink/Black missing texture.

![](https://cdn.discordapp.com/attachments/431778939799863296/511998714320125953/unknown.png)

**Comment by Level-5-Pidgey** [comment]
As an incentive to actually use the vastly superior Crafting _Stations_ made available from Tinkers' Construct, we have disabled crafting station recipes.
This is no longer a bug, and can instead be regarded as a "feature".

_In all seriousness, this is a bug caused by a mod update (FastWorkbench I believe) and should be fixed when the offending mod gets updated once more._
